apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lookup-cache
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    cd-layout: v2
    environment: platform3-dev
    service: lookup-cache
spec:
  project: io
  source:
    helm:
      valueFiles:
        - ../../../environments/platform3-dev/io/lookup-cache/microservice.yaml
        - ../../../environments/platform3-dev/io/lookup-cache/env.yaml
    path: charts/microservice
    repoURL: https://github.com/paramathmuni-sumanth/cd-v2.git
    targetRevision: main
  destination:
    namespace: io
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
