apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::620736318138:role/mtls-access-platform3-dev
  name: mtls-access-serviceaccount
  namespace: default
