kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-http-adaptor
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-06a8f7d5500927048
  directoryPerms: "777"
  gid: "0"
  uid: "0"
  # gidRangeStart: "50000" # optional /data/dump
  # gidRangeEnd: "50000" # optional
  basePath: "/websocket" # optional
  subPathPattern: "/data" # optional
  # ensureUniqueDirectory: "false" # optional
  # reuseAccessPoint: "false" # optional
