apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::689472371083:role/mtls-access-qa-prod
  name: mtls-access-serviceaccount
  namespace: default
