apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: http-adaptor-access-logs
  namespace: io
spec:
  selector:
    matchLabels:
      app: http-adaptor
  accessLogging:
    - providers:
      - name: access-log-provider
      filter:
        expression: response.code >= 300