apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::620736318138:role/recycle-opsworks-jsrt-s3-role-k8s
  name: recycle-opsworks-jsrt
  namespace: recycle-opsworks