apiVersion: batch/v1
kind: CronJob
metadata:
  name: mtls-cert-alert
  namespace: default
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: mtls-cert-alert-serviceaccount
          containers:
          - name: cert-alert
            image: 860378520032.dkr.ecr.us-east-1.amazonaws.com/mtls:cert-expiry-alert
            imagePullPolicy: Always
            env:
            - name: PRIVATE_CA_ARN
              value: "arn:aws:acm-pca:us-east-1:609704034070:certificate-authority/d86d620c-5425-4338-ad7f-6aed4b21d7ff"
            - name: BUCKET_NAME
              value: "acm-pca-audit-report-staging"
            - name: EMAIL_ADDRESS
              value: "devops-ms@celigo.com"
            - name: ENV_NAME
              value: "staging"
            - name: DAYS
              value: "7,15,30"
            - name: AWS_REGION
              value: "us-east-1"
            - name: SENDER_EMAIL
              value: "staging@celigo.com"
          restartPolicy: OnFailure