kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-07e2760af3aae0d2e
  directoryPerms: "777"
  gid: "0"
  uid: "0"
  # gidRangeStart: "50000" # optional /data/dump
  # gidRangeEnd: "50000" # optional
  basePath: "/data" # optional
  subPathPattern: "/dump" # optional
  ensureUniqueDirectory: "false" # optional
  # reuseAccessPoint: "false" # optional