apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::846543646911:role/mtls-access-platform4-dev
  name: mtls-access-serviceaccount
  namespace: default
