apiVersion: v2
name: prometheus
type: application
version: 28.3.0
appVersion: v3.9.1
dependencies:
- name: prometheus
  version: 28.3.0
  repository: https://raw.githubusercontent.com/celigo/helm-charts/gh-pages/
