apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::341118756977:role/mtls-cert-alert-role
  name: mtls-cert-alert-serviceaccount
  namespace: default