apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::860378520032:role/recycle-opsworks-jsrt-s3-role-k8s-production-na
  name: recycle-opsworks-jsrt
  namespace: recycle-opsworks