apiVersion: batch/v1
kind: CronJob
metadata:
  name: mtls-cert-alert
  namespace: default
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: mtls-cert-alert-serviceaccount
          containers:
          - name: cert-alert
            image: 341118756977.dkr.ecr.ap-south-1.amazonaws.com/mtls:cert-expiry-alert
            imagePullPolicy: Always
            env:
            - name: PRIVATE_CA_ARN
              value: "arn:aws:acm-pca:ap-south-1:689472371083:certificate-authority/f583ddd5-bda1-44ca-8610-251be27d329f"
            - name: BUCKET_NAME
              value: "acm-pca-audit-report-qa-prod"
            - name: EMAIL_ADDRESS
              value: "devops-ms@celigo.com"
            - name: ENV_NAME
              value: "qa-prod"
            - name: DAYS
              value: "7,15,30"
            - name: AWS_REGION
              value: "ap-south-1"
            - name: SENDER_EMAIL
              value: "staging@celigo.com"
          restartPolicy: OnFailure